# active spring boot profile
spring:
  profiles:
    active: dev
---
# common spring boot configuration
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  messages:
    basename: messages/messages_ko
    encoding: UTF-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  aop:
    auto: true
    proxy-target-class: true
---
# dev profile - spring boot configuration
spring:
   config:
      activate:
         on-profile: dev
   devtools:
      livereload:
         enabled: true
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
<<<<<<< HEAD
      url: jdbc:mysql://192.168.80.112:3307/mehago?characterEncoding=utf8
      username: mehago
      password: mehago
=======
      url: jdbc:mysql://127.0.0.1:3306/chat?characterEncoding=utf8
      username: bookmall_local
      password: bookmall_local
>>>>>>> 86aa8fb5b1b3129f47b98156544e5e574b9bcb37
   jwt:
      secret: PeAChHOng
      issuer: Mehago
    
---
# production profile - spring boot configuration
spring:
  config:
    activate:
      on-profile: production
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/chat?characterEncoding=utf8
    username: bookmall_local
    password: bookmall_local
---
# server
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

---
#mybatis
mybatis:
  config-location: classpath:mybatis/configuration.xml
#---
#logging
# logging:
#   config: classpath:logback.xml

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mehagoChat@gmail.com
    password: mehago123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true